### ISSUE TITLE
Broken Calendar section in README

### ISSUE THREAD

**Issue by Yanqiao4396** [CMPSC-305-Allegheny-College-Fall-2023/classDocs#1]
The HTML accidentally breaks and the iframe tag explicitly shows up in the Calendar section of README preview

**Comment by obonhamcarter** [comment]
Thank you for your issue and your feedback. I am trying to re-create the error and I find that if I am not logged into my campus gmail, then the the Google calendar will not show. Is this the issue to which you refer?
